[tox]
envlist =
    py{39,310,311,3.12}-django{32,40,41},
    py{310,311,312,313}-django{41,42,50}
    py{311,312,313}-django{51}


[testenv]
deps =
    django32: Django>=3.2,<4.0
    django40: Django>=4.0,<4.1
    django41: Django>=4.1,<4.2
    django42: Django>=4.2,<5.0
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
commands =
    python -m unittest discover -s tests

[flake8]
ignore = E501 W503